### ISSUE TITLE
Parent node of constructor declaration children not set

### ISSUE THREAD

**Issue by cal101** [rpau/javalang#23]
See pull request for fixes.

**Comment by cal101** [comment]
Question: Shall I close the merged issues or do you prefer to do that to be able to add a "fixed with version ..." info?

**Comment by rpau** [comment]
Close them directly :)---- On vie, 14 abr 2017 21:52:01 +0200  cal<notifications@github.com> wrote ----Question: Shall I close the merged issues or do you prefer to do that to be able to add a "fixed with version ..." info?  —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by cal101** [comment]
yes ma'am
